### ISSUE TITLE
Stats does not look right

### ISSUE THREAD

**Issue by jf908** [kidonng/unocss-preset-daisy#13]
The borders for stats doesn't seem to work properly for this preset.

![image](https://user-images.githubusercontent.com/2487520/225178873-4cafa8a1-b6bb-464b-93fe-dd10bf31bde5.png)

Using this code snippet from the DaisyUI docs:
```html
<div class="stats shadow">
  
  <div class="stat">
    <div class="stat-figure text-secondary">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-8 h-8 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
    </div>
    <div class="stat-title">Downloads</div>
    <div class="stat-value">31K</div>
    <div class="stat-desc">Jan 1st - Feb 1st</div>
  </div>
  
  <div class="stat">
    <div class="stat-figure text-secondary">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-8 h-8 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4"></path></svg>
    </div>
    <div class="stat-title">New Users</div>
    <div class="stat-value">4,200</div>
    <div class="stat-desc">↗︎ 400 (22%)</div>
  </div>
  
  <div class="stat">
    <div class="stat-figure text-secondary">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-8 h-8 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4"></path></svg>
    </div>
    <div class="stat-title">New Registers</div>
    <div class="stat-value">1,200</div>
    <div class="stat-desc">↘︎ 90 (14%)</div>
  </div>
  
</div>
```

**Comment by jf908** [comment]
It seems as though this style is missing a "px" as this doesn't work
```css
:where(.stats)>:not([hidden])~:not([hidden]) {
    border-top-width: calc(0 * calc(1 - var(--un-divide-y-reverse)));
    border-bottom-width: calc(0 * var(--un-divide-y-reverse));
}
```
but this does:
```css
:where(.stats)>:not([hidden])~:not([hidden]) {
    border-top-width: calc(0px * calc(1 - var(--un-divide-y-reverse)));
    border-bottom-width: calc(0px * var(--un-divide-y-reverse));
}
```
