### ISSUE TITLE
cannot use [directives transformer]() to apply component classes

### ISSUE THREAD

**Issue by KraXen72** [kidonng/unocss-preset-daisy#29]
i cannot use [directives transformer](https://unocss.dev/transformers/directives#directives-transformer) to apply component classes, for example:
```css
.form-input {
	--uno: "input input-primary";
}
.form-button {
	--uno: "btn btn-primary";
}
```
![image](https://github.com/kidonng/unocss-preset-daisy/assets/21956756/8c669afc-6cc9-4886-acf2-4bb43861b10c)

this is what i got after clicking copy rule in devtools:
```css
.form-button {
    .btn: is(input[type="checkbox"]),;
    .btn: is(input[type="checkbox"]):after,;
    .btn: active:hover,;
    .btn.btn-disabled,: ;
    .btn[disabled],: ;
    .btn: is(input[type="checkbox"]:checked),;
}
```
